language: python

python:
    - "3.3"
    - "3.4"

services:
    - redis-server

before_install:
    - sh bin/check_signoff.sh

install:
    - pip install coveralls flake8
    - pip install -e .
    - pip install -r requirements.txt

before_script:
    - flake8

script:
    - coverage run test_suite.py

after_success:
    - coveralls > /dev/null
